import os #ACCEDER A VARIABLES DEL SO
from dotenv import load_dotenv #IMPORTAR PARA CARGAR LAS VARIABLES DE ENTORNO

load_dotenv()

class Config:
    SQLALCHEMY_DATABASE_URI = os.getenv('DATABASE_URL') #CONEXION A LA BASE DE DATOS
    SQLALCHEMY_TRACK_MODIFICATIONS = False #DESACTIVAR EL SEGUIMIENTO DE MODIFICACIONES DE SQLALCHEMY
    SECRET_KEY = os.getenv('SECRET_KEY') #HABILITAR PETICIONES